import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { SessionProvider } from "next-auth/react";
import { Toaster } from 'react-hot-toast';
import LayoutWrapper from "@/components/LayoutWrapper/LayoutWrapper";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Drape Gear",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <SessionProvider>
          <StoreProvider>
            <LayoutWrapper>
              {children}
              <Toaster />
            </LayoutWrapper>
          </StoreProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
